spring:
  application:
    name: client-caller
  cloud:
    config:
      uri: http://localhost:8888
  config:
    import: "optional:configserver:"
#logging:
#  level:
#    org: debug

management:
  endpoint:
    beans:
      enabled: true
    info:
      enabled: true
