server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri:
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8091/eureka,
                  http://localhost:8092/eureka

